project_name: parsepico
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
- maintainer: Panagiotis Georgiadis <drpaneas@gmail.com>
  description: ParsePico is a tool to parse Pico-8 cartridges.
  homepage: https://github.com/drpaneas/parsepico
  license: MIT
  formats:
  - deb
  - rpm
  - apk